name: Build & Push Images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/lukasmanakel/olt-sentinel-backend:latest
  IMAGE_FRONTEND: ghcr.io/lukasmanakel/olt-sentinel-frontend:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:latest

      - name: Build e Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}:latest
